openapi: 3.0.3
info:
  version: '1'
  title: Generate thumbnails API
  description: API for generate thumbnails from an image
  license:
    name: MIT
servers:
  - url: https://localhost:3001
    description: Development server
  - url: https://k4xy6grwpb.execute-api.us-east-1.amazonaws.com
    description: Testing server
paths:
  /images:
    post:
      summary: Upload an image
      description: Upload an image to generate the thumbnails
      operationId: uploadImage
      tags:
        - images
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  $ref: '#/components/schemas/File'
            examples:
              image:
                $ref: '#/components/examples/ImageForUpload'
      responses:
        '200':
          $ref: '#/components/responses/ImageResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /images/{id}:
    get:
      summary: Get image by id
      description: Get an image by id
      operationId: getImage
      tags:
        - images
      parameters:
        - name: id
          in: path
          description: Image id
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ImageResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /thumbnails:
    get:
      summary: Get generated thumbnails
      description: 'Get all generated thumbnails'
      operationId: getThumbnails
      tags:
        - thumbnails
      parameters:
        - name: image_id
          in: query
          description: Image id
          required: true
          schema:
            type: string
        - name: size
          in: query
          description: Thumbnail size
          schema:
            $ref: '#/components/schemas/ThumbnailSize'
      responses:
        '200':
          $ref: '#/components/responses/ThumbnailsResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    Error:
      type: object
      description: Schema for represents an error on system
      properties:
        code:
          type: string
          description: Code that identifies the error on the system
        message:
          type: string
          description: Message that explain the error
    File:
      description: Represents a file
      type: string
      format: binary
    ThumbnailSize:
      description: Thumbnail size
      type: string
      enum:
        - 400x300
        - 160x120
        - 120x120
    Image:
      type: object
      properties:
        id:
          type: string
          description: Identifier of image
        name:
          type: string
          description: Name of image
        status:
          type: string
          description: Status of image
          enum:
            - UPLOADED
            - GENERATING_THUMBNAILS
            - THUMBNAILS_GENERATED
        url:
          type: string
          description: Url of image
        createdAt:
          type: string
          format: datetime
          description: Created at
        updatedAt:
          type: string
          format: datetime
          description: Updated at
    Thumbnail:
      type: object
      properties:
        id:
          type: string
          description: Identifier of thumbnail
        idImage:
          type: string
          description: Image id
        size:
          $ref: '#/components/schemas/ThumbnailSize'
        url:
          type: string
          description: Url of thumbnail
        createdAt:
          type: string
          format: datetime
          description: Created at
        updatedAt:
          type: string
          format: datetime
          description: Updated at
  responses:
    ValidationError:
      description: Error generated by validations on the input of the endpoint
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            GeneralValidationError:
              $ref: '#/components/examples/ValidationErrorResponse'
    InternalServerError:
      description: Error generated by an unexpected exception on system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            InternalServerError:
              $ref: '#/components/examples/InternalServerErrorResponse'
    NotFoundError:
      description: Error generated by the resource not exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            NotFoundError:
              $ref: '#/components/examples/NotFoundErrorResponse'
    ImageResponse:
      description: Your image has been uploaded successfully
      content:
        application/json:
          schema:
            type: object
            properties:
              image:
                $ref: '#/components/schemas/Image'
          examples:
            ImageResponse:
              $ref: '#/components/examples/ImageResponse'
    ThumbnailsResponse:
      description: Thumbnails retrieved with success
      content:
        application/json:
          schema:
            type: object
            properties:
              thumbnails:
                type: array
                description: Array of thumbnails
                items:
                  $ref: '#/components/schemas/Thumbnail'
          examples:
            ThumbanailsResponse:
              $ref: '#/components/examples/ThumbnailsResponse'
  examples:
    ValidationErrorResponse:
      summary: This is an example of validation error
      value:
        errors:
          IMAGES_2:
            code: IMAGES_2
            message: Image is not a valid JPEG image
    InternalServerErrorResponse:
      summary: This is an example of internal server error
      value:
        errors:
          500:
            code: "500"
            message: an unexpected error has occurred
    NotFoundErrorResponse:
      summary: This is an example of not found error
      value:
        errors:
          404:
            code: "404"
            message: Image not found
    ImageForUpload:
      summary: This is an example of image for upload
      externalValue: 'https://media-exp1.licdn.com/dms/image/C4E0BAQEmZ6-RlFCDNA/company-logo_200_200/0/1558041156098?e=2159024400&v=beta&t=YwiI8-Lol20SVbZXDGRp2keAKjtIuwLej4lvQqGA4AI'
    ImageResponse:
      summary: This is an example of image response
      value:
        image:
          id: 01FS6HBT4SXYDHRHMJNXG91HRV
          name: sinapsis-logo.jpeg
          status: THUMBNAILS_PENDING
          url: "http://localhost:4566/thumbnail-generator-api-images-dev/users/auth0%7C61d92971813c1d006a95f520/images/01FS6HBT4SXYDHRHMJNXG91HRV/foto%20perfil.jpeg?AWSAccessKeyId=default&Expires=1642030788&Signature=NTQBrvey3Bbpdk5THMxl5vaUdhk%3D"
          createdAt: "2022-01-12 01:59:48"
          updatedAt: null
    ThumbnailsResponse:
      summary: This is an example of thumbnails response
      value:
        thumbnails:
          - id: 01FS6DY3KMS0800WB2K5S6MV3N
            idImage: 01FS6DY39H94V6BWWAPSPE98HJ
            size: 120x120
            url: "http://localhost:4566/thumbnail-generator-api-images-dev/users/dev-user/images/01FS68NKY8DWTXR5CR7AX0PVRW/thumbnails/200%40160x120.jpeg?AWSAccessKeyId=default&Expires=1642031156&Signature=YTN24A5MWNVDkyUmTlSBVp398Ws%3D"
            createdAt: "2022-01-12 01:59:48"
            updatedAt: null
          - id: 01FS6DY4ZB1TN2MSW23W3DSK07
            idImage: 01FS6DY39H94V6BWWAPSPE98HJ
            size: 400x300
            url: "http://localhost:4566/thumbnail-generator-api-images-dev/users/dev-user/images/01FS68NKY8DWTXR5CR7AX0PVRW/thumbnails/200%40400x300.jpeg?AWSAccessKeyId=default&Expires=1642031156&Signature=YTN24A5MWNVDkyUmTlSBVp398Ws%3D"
            createdAt: "2022-01-12 01:59:48"
            updatedAt: null
  securitySchemes:
    auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - auth: []

